def on_button_pressed_ab():
    basic.show_number(10)
    basic.pause(100)
    basic.show_number(9)
    basic.pause(100)
    basic.show_number(8)
    basic.pause(100)
    basic.show_number(7)
    basic.pause(100)
    basic.show_number(6)
    basic.pause(100)
    basic.show_number(5)
    basic.pause(100)
    basic.show_number(4)
    basic.pause(100)
    basic.show_number(3)
    basic.pause(100)
    basic.show_number(2)
    basic.pause(100)
    basic.show_number(1)
    for index in range(10):
        basic.show_string("GO GO GO")
input.on_button_pressed(Button.AB, on_button_pressed_ab)
